// resources/js/map-workspace/panels/LayerPanel.jsx
import { useEffect, useState } from 'react';
import {
    DndContext,
    closestCenter,
    KeyboardSensor,
    PointerSensor,
    useSensor,
    useSensors,
} from '@dnd-kit/core';
import {
    arrayMove,
    SortableContext,
    sortableKeyboardCoordinates,
    useSortable,
    verticalListSortingStrategy,
} from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { Eye, EyeOff, Layers, Plus, Trash2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
    Sheet,
    SheetContent,
    SheetDescription,
    SheetFooter,
    SheetHeader,
    SheetTitle,
} from '@/components/ui/sheet';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { useMapStore } from '../store/mapStore';

function SortableLayerItem({ layer, selectedLayerId, onSelect, onToggleVisibility, onRemove, readOnly = false }) {
    const { attributes, listeners, setNodeRef, transform, transition } = useSortable({
        id: layer.id,
    });

    const style = {
        transform: CSS.Transform.toString(transform),
        transition,
    };

    return (
        <div
            ref={setNodeRef}
            style={style}
            className={`layer-item${layer.id === selectedLayerId ? ' active' : ''}`}
            onClick={() => onSelect(layer.id)}
            {...(readOnly ? {} : attributes)}
            {...(readOnly ? {} : listeners)}
        >
            <div className="layer-info">
                <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="size-6"
                    onPointerDown={(event) => event.stopPropagation()}
                    onClick={(event) => {
                        event.stopPropagation();
                        onToggleVisibility(layer.id);
                    }}
                    aria-label={layer.visible ? 'Hide layer' : 'Show layer'}
                >
                    {layer.visible ? (
                        <Eye className="size-4" strokeWidth={1.75} aria-hidden="true" />
                    ) : (
                        <EyeOff className="size-4" strokeWidth={1.75} aria-hidden="true" />
                    )}
                </Button>
                <span className="layer-name">{layer.name}</span>
            </div>
            {readOnly ? null : (
            <div className="layer-actions">
                <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="size-6 text-destructive hover:text-destructive"
                    onPointerDown={(event) => event.stopPropagation()}
                    onClick={(event) => {
                        event.stopPropagation();
                        onRemove(layer.id);
                    }}
                    aria-label="Remove layer"
                >
                    <Trash2 className="size-4" strokeWidth={1.75} aria-hidden="true" />
                </Button>
            </div>
            )}
        </div>
    );
}

const emptyLayerForm = {
    type: 'wms',
    name: '',
    url: '',
    layers: '',
};

export default function LayerPanel({ onClose, onLayerSelected, readOnly = false }) {
    const layers = useMapStore((state) => state.layers);
    const selectedLayerId = useMapStore((state) => state.selectedLayer);
    const availableBasemaps = useMapStore((state) => state.availableBasemaps);
    const basemap = useMapStore((state) => state.basemap);
    const setBasemap = useMapStore((state) => state.setBasemap);
    const selectLayer = useMapStore((state) => state.selectLayer);
    const toggleLayerVisibility = useMapStore((state) => state.toggleLayerVisibility);
    const removeLayer = useMapStore((state) => state.removeLayer);
    const addLayer = useMapStore((state) => state.addLayer);
    const updateLayerOrder = useMapStore((state) => state.updateLayerOrder);

    const [showModal, setShowModal] = useState(false);
    const [layerSource, setLayerSource] = useState('custom');
    const [selectedGeoServerLayer, setSelectedGeoServerLayer] = useState('');
    const [publishedLayers, setPublishedLayers] = useState([]);
    const [newLayer, setNewLayer] = useState({ ...emptyLayerForm });
    const [selectedBasemap, setSelectedBasemap] = useState(basemap);

    const sensors = useSensors(
        useSensor(PointerSensor, { activationConstraint: { distance: 6 } }),
        useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates })
    );

    const loadPublishedLayers = async () => {
        try {
            const response = await window.axios.get('/layers', {
                headers: { Accept: 'application/json' },
                params: { published: 1 },
            });

            const payload = response.data?.data || response.data || [];
            const list = (Array.isArray(payload) ? payload : []).filter((layer) => layer.published);
            setPublishedLayers(list);
        } catch (error) {
            console.error('Error loading published layers:', error);
        }
    };

    useEffect(() => {
        loadPublishedLayers();
    }, []);

    useEffect(() => {
        setSelectedBasemap(basemap);
    }, [basemap]);

    const closeModal = () => {
        setShowModal(false);
        setLayerSource('custom');
        setSelectedGeoServerLayer('');
        setNewLayer({ ...emptyLayerForm });
    };

    const handleAddLayer = () => {
        if (!newLayer.name) {
            alert('Please fill in all required fields');
            return;
        }

        if (newLayer.type === 'wms' && newLayer.layerId) {
            addLayer({
                id: newLayer.layerId,
                name: newLayer.name,
                type: 'wms',
                url: newLayer.url,
                layers: newLayer.layers,
                wmsParams: newLayer.wmsParams || { SORTING: 'acquired D' },
                visible: true,
                opacity: 1,
            });
            closeModal();
            return;
        }

        if (newLayer.type === 'mvt' && newLayer.layerId) {
            addLayer({
                id: newLayer.layerId,
                name: newLayer.name,
                type: 'mvt',
                mvtUrl: `/api/layers/${newLayer.layerId}/tiles/{z}/{x}/{y}.mvt`,
                url: `/api/layers/${newLayer.layerId}/geojson`,
                visible: true,
                opacity: 1,
                style: newLayer.styleConfig || {},
                style_config: newLayer.styleConfig || {},
                geometry_type: newLayer.geometry_type || null,
                timeField: newLayer.timeField || null,
            });
            closeModal();
            return;
        }

        if (!newLayer.url) {
            alert('Please fill in all required fields');
            return;
        }

        addLayer({
            id: Date.now().toString(),
            name: newLayer.name,
            type: newLayer.type,
            url: newLayer.url,
            layers: newLayer.layers,
            visible: true,
            opacity: 1,
            style: {},
        });
        closeModal();
    };

    const onGeoServerLayerSelect = (layerId) => {
        setSelectedGeoServerLayer(layerId);
        const layer = publishedLayers.find((item) => String(item.id) === String(layerId));
        if (!layer) {
            return;
        }

        const geoserverUrl =
            import.meta.env.VITE_GEOSERVER_URL || 'http://127.0.0.1:8081/geoserver';

        if (layer.geometry_type === 'Raster') {
            const workspace = layer.geoserver_workspace;
            const coverage = layer.geoserver_layer_name || layer.table_name;
            setNewLayer({
                type: 'wms',
                layerId: layer.id,
                name: layer.name,
                url: `${geoserverUrl}/wms`,
                layers: workspace ? `${workspace}:${coverage}` : coverage,
                wmsParams: layer.metadata?.wms_params || { SORTING: 'acquired D' },
            });
            return;
        }

        // Prefer PostGIS MVT; keep WMS metadata as fallback fields.
        setNewLayer({
            type: 'mvt',
            layerId: layer.id,
            name: layer.name,
            url: `${geoserverUrl}/wms`,
            layers:
                layer.geoserver_layer_name ||
                `${layer.geoserver_workspace}:${layer.table_name}`,
                styleConfig: layer.style_config || {},
                geometry_type: layer.geometry_type,
                timeField: layer.metadata?.time_field || null,
        });
    };

    const handleDragEnd = (event) => {
        const { active, over } = event;
        if (!over || active.id === over.id) {
            return;
        }

        const oldIndex = layers.findIndex((layer) => layer.id === active.id);
        const newIndex = layers.findIndex((layer) => layer.id === over.id);
        updateLayerOrder(arrayMove(layers, oldIndex, newIndex));
    };

    const handleRemove = (layerId) => {
        if (confirm('Are you sure you want to remove this layer?')) {
            removeLayer(layerId);
        }
    };

    return (
        <div className="layer-panel">
            <div className="panel-header">
                <h5>Layers</h5>
                <div className="flex items-center gap-1">
                    {readOnly ? null : (
                    <Button type="button" size="sm" className="h-8 gap-1.5" onClick={() => setShowModal(true)}>
                        <Plus className="size-3.5" strokeWidth={1.75} />
                        Add Layer
                    </Button>
                    )}
                    {onClose ? (
                        <Button type="button" variant="ghost" size="icon" className="size-8" onClick={onClose} aria-label="Close">
                            <X className="size-4" />
                        </Button>
                    ) : null}
                </div>
            </div>

            {readOnly ? null : (
            <div className="basemap-selector">
                <Label className="mb-2">Base Map</Label>
                <Select
                    value={selectedBasemap}
                    onValueChange={(value) => {
                        setSelectedBasemap(value);
                        setBasemap(value);
                    }}
                >
                    <SelectTrigger className="w-full bg-background" aria-label="Base map">
                        <SelectValue placeholder="Base map" />
                    </SelectTrigger>
                    <SelectContent>
                        {availableBasemaps.map((item) => (
                            <SelectItem key={item.id} value={item.id}>
                                {item.name}
                            </SelectItem>
                        ))}
                    </SelectContent>
                </Select>
            </div>
            )}

            <div className="layers-list">
                {layers.length === 0 ? (
                    <div className="empty-state">
                        <Layers className="glyph lg" strokeWidth={1.5} aria-hidden="true" />
                        <p>No layers on this map.</p>
                        {readOnly ? null : (
                        <a href="/imports/create" className="text-sm font-medium text-primary underline-offset-4 hover:underline">
                            Import data
                        </a>
                        )}
                    </div>
                ) : (
                    <DndContext
                        sensors={sensors}
                        collisionDetection={closestCenter}
                        onDragEnd={handleDragEnd}
                    >
                        <SortableContext
                            items={layers.map((layer) => layer.id)}
                            strategy={verticalListSortingStrategy}
                        >
                            <div className="layer-items">
                                {layers.map((layer) => (
                                    <SortableLayerItem
                                        key={layer.id}
                                        layer={layer}
                                        selectedLayerId={selectedLayerId}
                                        readOnly={readOnly}
                                        onSelect={(id) => {
                                            selectLayer(id);
                                            onLayerSelected?.(id);
                                        }}
                                        onToggleVisibility={toggleLayerVisibility}
                                        onRemove={handleRemove}
                                    />
                                ))}
                            </div>
                        </SortableContext>
                    </DndContext>
                )}
            </div>

            <Sheet
                modal={false}
                open={showModal}
                onOpenChange={(open) => {
                    if (!open) closeModal();
                }}
            >
                <SheetContent
                    side="right"
                    showOverlay={false}
                    onInteractOutside={(event) => event.preventDefault()}
                    onPointerDownOutside={(event) => event.preventDefault()}
                    onFocusOutside={(event) => event.preventDefault()}
                    className="inset-y-auto top-[4.25rem] right-[1.65rem] bottom-auto z-40 h-auto max-h-[calc(100vh-7.5rem)] w-[min(22rem,calc(100vw-7rem))] gap-0 overflow-hidden rounded-xl border p-0 shadow-lg sm:max-w-none"
                >
                    <SheetHeader className="border-b">
                        <SheetTitle>Add Layer</SheetTitle>
                        <SheetDescription>Add a custom service or a published GeoServer layer. The map stays usable.</SheetDescription>
                    </SheetHeader>
                    <div className="grid min-h-0 flex-1 gap-4 overflow-y-auto p-4">
                        <div className="grid gap-2">
                            <Label htmlFor="layer-source">Layer source</Label>
                            <Select
                                value={layerSource}
                                onValueChange={(value) => {
                                    setLayerSource(value);
                                    if (value === 'geoserver') {
                                        loadPublishedLayers();
                                    }
                                }}
                            >
                                <SelectTrigger id="layer-source" className="w-full">
                                    <SelectValue />
                                </SelectTrigger>
                                <SelectContent className="z-[90]">
                                    <SelectItem value="custom">Custom URL</SelectItem>
                                    <SelectItem value="geoserver">From GeoServer</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>

                        {layerSource === 'geoserver' ? (
                            <div className="grid gap-2">
                                <Label htmlFor="published-layers">Published layers</Label>
                                <Select
                                    value={selectedGeoServerLayer || undefined}
                                    onValueChange={onGeoServerLayerSelect}
                                >
                                    <SelectTrigger id="published-layers" className="w-full">
                                        <SelectValue placeholder="Select a published layer..." />
                                    </SelectTrigger>
                                    <SelectContent className="z-[90]">
                                        {publishedLayers.map((layer) => (
                                            <SelectItem key={layer.id} value={String(layer.id)}>
                                                {layer.name} ({layer.geometry_type})
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                                {publishedLayers.length === 0 ? (
                                    <p className="text-xs text-muted-foreground">
                                        No published layers yet.{' '}
                                        <a href="/layers" className="font-medium text-primary underline-offset-4 hover:underline">
                                            Publish a layer
                                        </a>
                                        {' '}or{' '}
                                        <a href="/imports/create" className="font-medium text-primary underline-offset-4 hover:underline">
                                            import a dataset
                                        </a>
                                        .
                                    </p>
                                ) : (
                                    <p className="text-xs text-muted-foreground">Only published layers are shown.</p>
                                )}
                            </div>
                        ) : null}

                        {layerSource === 'custom' ? (
                            <>
                                <div className="grid gap-2">
                                    <Label htmlFor="layer-type">Layer type</Label>
                                    <Select
                                        value={newLayer.type}
                                        onValueChange={(value) =>
                                            setNewLayer((prev) => ({ ...prev, type: value }))
                                        }
                                    >
                                        <SelectTrigger id="layer-type" className="w-full">
                                            <SelectValue />
                                        </SelectTrigger>
                                        <SelectContent className="z-[90]">
                                            <SelectItem value="wms">WMS Layer</SelectItem>
                                            <SelectItem value="wfs">WFS Layer</SelectItem>
                                            <SelectItem value="vector">Vector Layer (GeoJSON)</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </div>
                                <div className="grid gap-2">
                                    <Label htmlFor="layer-name">Layer name</Label>
                                    <Input
                                        id="layer-name"
                                        value={newLayer.name}
                                        onChange={(event) =>
                                            setNewLayer((prev) => ({ ...prev, name: event.target.value }))
                                        }
                                        placeholder="Enter layer name"
                                    />
                                </div>
                                <div className="grid gap-2">
                                    <Label htmlFor="layer-url">URL</Label>
                                    <Input
                                        id="layer-url"
                                        value={newLayer.url}
                                        onChange={(event) =>
                                            setNewLayer((prev) => ({ ...prev, url: event.target.value }))
                                        }
                                        placeholder="Enter layer URL"
                                    />
                                </div>
                                {newLayer.type === 'wms' ? (
                                    <div className="grid gap-2">
                                        <Label htmlFor="layer-names">Layer names</Label>
                                        <Input
                                            id="layer-names"
                                            value={newLayer.layers}
                                            onChange={(event) =>
                                                setNewLayer((prev) => ({ ...prev, layers: event.target.value }))
                                            }
                                            placeholder="e.g., workspace:layername"
                                        />
                                    </div>
                                ) : null}
                            </>
                        ) : null}

                        {layerSource === 'geoserver' && selectedGeoServerLayer ? (
                            <>
                                <div className="grid gap-2">
                                    <Label htmlFor="gs-name">Layer name</Label>
                                    <Input id="gs-name" value={newLayer.name} readOnly />
                                </div>
                                <div className="grid gap-2">
                                    <Label htmlFor="gs-url">GeoServer URL</Label>
                                    <Input id="gs-url" value={newLayer.url} readOnly />
                                </div>
                                <div className="grid gap-2">
                                    <Label htmlFor="gs-layer">Layer</Label>
                                    <Input id="gs-layer" value={newLayer.layers} readOnly />
                                </div>
                            </>
                        ) : null}
                    </div>
                    <SheetFooter className="flex-row justify-end border-t">
                        <Button type="button" variant="outline" onClick={closeModal}>
                            Cancel
                        </Button>
                        <Button type="button" onClick={handleAddLayer}>
                            Add Layer
                        </Button>
                    </SheetFooter>
                </SheetContent>
            </Sheet>
        </div>
    );
}

// resources/js/components/map-builder/LayerPanel.vue
<template>
    <div class="layer-panel">
        <div class="panel-header">
            <h5>Layers</h5>
            <button @click="showAddLayerModal" class="btn btn-sm btn-primary">
                <i class="fas fa-plus"></i> Add Layer
            </button>
        </div>

        <div class="basemap-selector">
            <label>Base Map:</label>
            <select v-model="selectedBasemap" @change="changeBasemap" class="form-select form-select-sm">
                <option v-for="basemap in availableBasemaps" :key="basemap.id" :value="basemap.id">
                    {{ basemap.name }}
                </option>
            </select>
        </div>

        <div class="layers-list">
            <div v-if="layers.length === 0" class="empty-state">
                <i class="fas fa-layer-group fa-3x text-muted"></i>
                <p>No layers added yet</p>
            </div>

            <draggable
                v-model="layersList"
                @end="onLayerReorder"
                item-key="id"
                class="layer-items"
            >
                <template #item="{ element }">
                    <div
                        class="layer-item"
                        :class="{ 'active': element.id === selectedLayerId }"
                        @click="selectLayer(element.id)"
                    >
                        <div class="layer-info">
                            <button
                                @click.stop="toggleVisibility(element.id)"
                                class="btn btn-sm btn-link visibility-btn"
                            >
                                <i :class="element.visible ? 'fas fa-eye' : 'fas fa-eye-slash'"></i>
                            </button>
                            <span class="layer-name">{{ element.name }}</span>
                        </div>
                        <div class="layer-actions">
                            <button
                                @click.stop="removeLayer(element.id)"
                                class="btn btn-sm btn-link text-danger"
                            >
                                <i class="fas fa-trash"></i>
                            </button>
                        </div>
                    </div>
                </template>
            </draggable>
        </div>

        <!-- Add Layer Modal -->
        <div v-if="showModal" class="modal-overlay" @click="closeModal">
            <div class="modal-content" @click.stop>
                <div class="modal-header">
                    <h5>Add Layer</h5>
                    <button @click="closeModal" class="btn-close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Layer Source:</label>
                        <select v-model="layerSource" @change="onSourceChange" class="form-select">
                            <option value="custom">Custom URL</option>
                            <option value="geoserver">From GeoServer</option>
                        </select>
                    </div>

                    <div v-if="layerSource === 'geoserver'" class="mb-3">
                        <label class="form-label">Published Layers:</label>
                        <select v-model="selectedGeoServerLayer" @change="onGeoServerLayerSelect" class="form-select">
                            <option value="">Select a published layer...</option>
                            <option v-for="layer in publishedLayers" :key="layer.id" :value="layer.id">
                                {{ layer.name }} ({{ layer.geometry_type }})
                            </option>
                        </select>
                        <small class="text-muted">Only published layers are shown</small>
                    </div>

                    <div v-if="layerSource === 'custom'">
                        <div class="mb-3">
                            <label class="form-label">Layer Type:</label>
                            <select v-model="newLayer.type" class="form-select">
                                <option value="wms">WMS Layer</option>
                                <option value="wfs">WFS Layer</option>
                                <option value="vector">Vector Layer (GeoJSON)</option>
                            </select>
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Layer Name:</label>
                            <input v-model="newLayer.name" type="text" class="form-control" placeholder="Enter layer name">
                        </div>

                        <div class="mb-3">
                            <label class="form-label">URL:</label>
                            <input v-model="newLayer.url" type="text" class="form-control" placeholder="Enter layer URL">
                        </div>

                        <div v-if="newLayer.type === 'wms'" class="mb-3">
                            <label class="form-label">Layer Names:</label>
                            <input v-model="newLayer.layers" type="text" class="form-control" placeholder="e.g., workspace:layername">
                        </div>
                    </div>

                    <div v-if="layerSource === 'geoserver' && selectedGeoServerLayer">
                        <div class="mb-3">
                            <label class="form-label">Layer Name:</label>
                            <input v-model="newLayer.name" type="text" class="form-control" readonly>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">GeoServer URL:</label>
                            <input v-model="newLayer.url" type="text" class="form-control" readonly>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Layer:</label>
                            <input v-model="newLayer.layers" type="text" class="form-control" readonly>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button @click="closeModal" class="btn btn-secondary">Cancel</button>
                    <button @click="addLayer" class="btn btn-primary">Add Layer</button>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { useMapStore } from '../../stores/mapStore';
import draggable from 'vuedraggable';

const mapStore = useMapStore();
const showModal = ref(false);
const layerSource = ref('custom');
const selectedGeoServerLayer = ref('');
const publishedLayers = ref([]);
const newLayer = ref({
    type: 'wms',
    name: '',
    url: '',
    layers: ''
});

const layers = computed(() => mapStore.layers);
const layersList = computed({
    get: () => mapStore.layers,
    set: (value) => mapStore.updateLayerOrder(value)
});
const selectedLayerId = computed(() => mapStore.selectedLayer);
const availableBasemaps = computed(() => mapStore.availableBasemaps);
const selectedBasemap = ref(mapStore.basemap);

// Load published layers when component mounts
onMounted(async () => {
    await loadPublishedLayers();
});

const selectLayer = (layerId) => {
    mapStore.selectLayer(layerId);
};

const toggleVisibility = (layerId) => {
    mapStore.toggleLayerVisibility(layerId);
};

const removeLayer = (layerId) => {
    if (confirm('Are you sure you want to remove this layer?')) {
        mapStore.removeLayer(layerId);
    }
};

const onLayerReorder = () => {
    // Layer order is already updated via v-model
};

const changeBasemap = () => {
    mapStore.setBasemap(selectedBasemap.value);
};

const showAddLayerModal = () => {
    showModal.value = true;
};

const closeModal = () => {
    showModal.value = false;
    layerSource.value = 'custom';
    selectedGeoServerLayer.value = '';
    newLayer.value = {
        type: 'wms',
        name: '',
        url: '',
        layers: ''
    };
};

const addLayer = () => {
    if (!newLayer.value.name || !newLayer.value.url) {
        alert('Please fill in all required fields');
        return;
    }

    const layer = {
        id: Date.now().toString(),
        name: newLayer.value.name,
        type: newLayer.value.type,
        url: newLayer.value.url,
        layers: newLayer.value.layers,
        visible: true,
        opacity: 1,
        style: {}
    };

    mapStore.addLayer(layer);
    closeModal();
};

const loadPublishedLayers = async () => {
    try {
        // Fetch published layers from the backend
        const response = await window.axios.get('/layers');
        if (response.data && response.data.data) {
            publishedLayers.value = response.data.data.filter(layer => layer.published);
        }
    } catch (error) {
        console.error('Error loading published layers:', error);
    }
};

const onSourceChange = () => {
    if (layerSource.value === 'geoserver') {
        loadPublishedLayers();
    }
};

const onGeoServerLayerSelect = () => {
    const layer = publishedLayers.value.find(l => l.id === parseInt(selectedGeoServerLayer.value));
    if (layer) {
        // Get GeoServer base URL from config or use default
        const geoserverUrl = import.meta.env.VITE_GEOSERVER_URL || 'http://localhost:8080/geoserver';
        
        newLayer.value = {
            type: 'wms',
            name: layer.name,
            url: `${geoserverUrl}/wms`,
            layers: layer.geoserver_layer_name || `${layer.geoserver_workspace}:${layer.table_name}`
        };
    }
};
</script>

<style scoped>
.layer-panel {
    display: flex;
    flex-direction: column;
    height: 100%;
}

.panel-header {
    padding: 1rem;
    border-bottom: 1px solid #ddd;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.panel-header h5 {
    margin: 0;
}

.basemap-selector {
    padding: 1rem;
    border-bottom: 1px solid #ddd;
}

.basemap-selector label {
    font-weight: 600;
    margin-bottom: 0.5rem;
    display: block;
}

.layers-list {
    flex: 1;
    overflow-y: auto;
    padding: 0.5rem;
}

.empty-state {
    text-align: center;
    padding: 2rem;
    color: #6c757d;
}

.empty-state i {
    margin-bottom: 1rem;
}

.layer-items {
    list-style: none;
    padding: 0;
    margin: 0;
}

.layer-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.75rem;
    margin-bottom: 0.5rem;
    background: #f8f9fa;
    border-radius: 4px;
    cursor: pointer;
    transition: all 0.2s;
}

.layer-item:hover {
    background: #e9ecef;
}

.layer-item.active {
    background: #007bff;
    color: white;
}

.layer-info {
    display: flex;
    align-items: center;
    gap: 0.5rem;
}

.visibility-btn {
    padding: 0.25rem 0.5rem;
}

.layer-name {
    font-weight: 500;
}

.layer-actions {
    display: flex;
    gap: 0.25rem;
}

.modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
}

.modal-content {
    background: white;
    border-radius: 8px;
    width: 90%;
    max-width: 500px;
    max-height: 90vh;
    overflow-y: auto;
}

.modal-header {
    padding: 1rem;
    border-bottom: 1px solid #ddd;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.modal-header h5 {
    margin: 0;
}

.modal-body {
    padding: 1rem;
}

.modal-footer {
    padding: 1rem;
    border-top: 1px solid #ddd;
    display: flex;
    justify-content: flex-end;
    gap: 0.5rem;
}
</style>
